language: ruby
rvm:
- 2.3.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
    - master
    - develop

sudo: required

before_install:
  - nvm install node
  - ruby -v

install:
  - gem install bundler
  - bundle install
  - npm install -g firebase-tools

before_script:
  - jekyll build
  - if [ $TRAVIS_BRANCH == "master" ]; then htmlproofer _site --http-status-ignore "999"; fi

script:
  - if [ $TRAVIS_BRANCH == "master" ]; then export FIREBASE_DEPLOY_KEY=$FIREBASE_DEPLOY_KEY_PROD; else FIREBASE_DEPLOY_KEY=$FIREBASE_DEPLOY_KEY_DEV; fi
  - if [ $TRAVIS_BRANCH == "master" ]; then export FIREBASE_PROJECT="default"; else export FIREBASE_PROJECT="develop"; fi
  - echo $FIREBASE_PROJECT
  - firebase use $FIREBASE_PROJECT --token $FIREBASE_DEPLOY_KEY
  - export COMMIT_HASH=$(echo $TRAVIS_COMMIT | cut -b -6)
- firebase deploy -m "build $TRAVIS_BUILD_NUMBER $TRAVIS_BRANCH/$COMMIT_HASH" --non-interactive --token $FIREBASE_DEPLOY_KEY
