language: node_js
node_js:
  - "6.11"

branches:
  only:
    - master

before_script:
  - rvm install 2.2
  - rvm use 2.2
  - . $HOME/.nvm/nvm.sh && nvm install 6.1 && nvm use 6.1
  - gem install bundler
  - bundle check || bundle install
  - npm install -g firebase-tools

script:
  - jekyll build

after_success:
  - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
