language: node_js
node_js:
  - "6.11"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - jekyll build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
